# Generated by Django 2.2.5 on 2020-09-12 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20200912_1731'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='check_ouy',
            new_name='check_out',
        ),
    ]
